version: '3'

services:
  app:
    container_name: nest-ping-api-app
    image: nestjs-dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
    volumes:
      - ../:/usr/code/src
      - /app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - dev-db
    command: npx nest start --watch

  dev-db:
    image: postgres:14.2-alpine
    container_name: nest-ping-api-dev-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_node
      - POSTGRES_PASSWORD=password_node
      - POSTGRES_DB=db_node
    ports:
      - 5833:5432

  test-db:
    container_name: nest-ping-api-test-db
    image: postgres:14-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: node

volumes:
  postgres_data: {}
